name: metal_calculator
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Provider
  provider: ^6.1.2

  # Router
  go_router: ^14.6.1

  # Storage
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  assets:
    - assets/images/

  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/src/common/l10n/
  output_dir: lib/src/common/l10n/generated/